sudo: required

services:
  - docker

language: python

# command to install dependencies
install:
  - pip3 install -r requirements.txt
# command to run tests
script:
  - python3 -m pytest -v

after_success:
  - sh .travis/deploy_dockerhub.sh