sudo: required

services:
  - docker

language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - pip3 install -r requirements.txt
# command to run tests
script:
  - python3 -m pytest -v

after_success:
  - sh .travis/deploy_dockerhub.sh